### ISSUE TITLE
Feature request: compatibility with imgur links and imgur plugin

### ISSUE THREAD

**Issue by BlitzVI** [Hosstell/image-tools-obsidian-plugin#1]
Hey!
this seems like a really handy plugin to have but if it were to be compatible with imgur links it would be much more versatile. Especially for me as i use a lot of screenshots in my notes so saving all of those on my computer isn't the best idea.
I hope you can implement this feature in the upcoming updates!
Thank you!

**Comment by Hosstell** [comment]
Hello, @BlitzVI!
Thank for your comment!

In new version (1.1.0) the plugin can work with imgur links. =)
